readmeとかを自動でお膳立てする機能追加

diff --git a/gitp b/gitp
--- a/gitp
+++ b/gitp
@@ -32,7 +32,29 @@ gitcommit() {
 	git commit -m "$1"
 }
 
-while getopts n:f:h:s OPT
+makeGitFiles() {
+	notgitrepo=`git status 2>&1 | grep 'not a git repository'`
+	if [ -n "${notgitrepo}" ]; then
+		echo "Warning: It looks like this is not a git repository yet."
+		echo "Create git files? [y/n]"
+		read answer
+		case "$answer" in [yY]*) ;; *) echo "abort." ; exit 1 ;; esac
+	fi
+	if [ -z `ls -a | grep --ignore-case readme` ]; then
+		touch readme.md
+		showstatus "create: readme.md"
+	fi
+	if [ -z `ls -a | grep --ignore-case .gitignore` ]; then
+		touch .gitignore
+		showstatus "create: .gitignore"
+	fi
+	if [ -z `ls -a | grep --ignore-case .gitattributes` ]; then
+		touch .gitattributes
+		showstatus "create: .gitattributes"
+	fi
+}
+
+while getopts n:f:h:s:m OPT
 do
 	case $OPT in
 		n)	status="no_push"
@@ -52,6 +74,10 @@ do
 			git status
 			exit 0
 			;;
+		m)	status="make_gitfiles"
+			makeGitFiles
+			exit 0
+			;;
 		\?) status="unexpected_option"
 			showstatus error
 			gethelp
@@ -61,8 +87,6 @@ do
 done
 
 if [ $# -eq 0 ]; then
-	# gethelp
-	# exit 1
 	showstatus pulling...
 	git pull
 	exit 0
