:sparkles:.gitignoreがないと怒るようになった

diff --git a/gitp b/gitp
--- a/gitp
+++ b/gitp
@@ -20,6 +20,13 @@ gitcommit() {
 		read answer
 		case "$answer" in [yY]*) ;; *) echo "abort." ; exit 1 ;; esac
 	fi
+	exist_gitignore=`ls -a | grep .gitignore`
+	if [ -z "${exist_gitignore}" ]; then
+		echo "Warning: It looks like \".gitignore\" does not exist."
+		echo "Are you sure? [y/n]"
+		read answer
+		case "$answer" in [yY]*) ;; *) echo "abort." ; exit 1 ;; esac
+	fi
 	git add -A
 	git commit -m "$1"
 }
